---

- name: Get encrypted shares (locked)
  become: true
  ansible.builtin.command: "/usr/syno/sbin/synoshare --enum ENC"
  register: encshares
  changed_when: false

- name: "Encrypted shares found"
  ansible.builtin.debug:
    var: encshares.stdout_lines
  when: encshares.stdout_lines | length > 2

- name: Mount encrypted shares
  become: true
  ansible.builtin.command: "/usr/syno/sbin/synoshare --enc_mount {{ item | quote }} {{ encpwd | quote }}"
  loop: "{{ encshares.stdout_lines | reject('search', 'Share Enum Arguments') | reject('search', 'Listed:') | list }}"
  when: encshares.stdout_lines | length > 2
  changed_when: true

- name: "No encrypted shares found"
  ansible.builtin.debug:
    msg: "No encrypted shares to mount."
  when: encshares.stdout_lines | length <= 2
